[package]
name = "meteo-wizard"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 0
debug = true
split-debuginfo = '...'  # Platform-specific.


[profile.release]
opt-level = 3
debug = false
strip = "debuginfo"
lto = true
panic = 'abort'

[dependencies]
serde_json = "1.0.122"
curl = "0.4.46"
thiserror = "1.0.63"
chrono = "0.4.38"
chrono-tz = "0.9.0"
log = { version = "0.4.22", features = ["std"] }
env_logger = "0.11.5"
serde = { version = "1.0.205", features = ["derive"] }
